<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KabupatenKotaMSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $kabupatenKota = [
            ['id'=> 1101, 'kabupatenkota'=> 'KABUPATEN SIMEULUE', 'objectprovinsifk'=> 11],
            ['id'=> 1102, 'kabupatenkota'=> 'KABUPATEN ACEH SINGKIL', 'objectprovinsifk'=> 11],
            ['id'=> 1103, 'kabupatenkota'=> 'KABUPATEN ACEH SELATAN', 'objectprovinsifk'=> 11],
            ['id'=> 1104, 'kabupatenkota'=> 'KABUPATEN ACEH TENGGARA', 'objectprovinsifk'=> 11],
            ['id'=> 1105, 'kabupatenkota'=> 'KABUPATEN ACEH TIMUR', 'objectprovinsifk'=> 11],
            ['id'=> 1106, 'kabupatenkota'=> 'KABUPATEN ACEH TENGAH', 'objectprovinsifk'=> 11],
            ['id'=> 1107, 'kabupatenkota'=> 'KABUPATEN ACEH BARAT', 'objectprovinsifk'=> 11],
            ['id'=> 1108, 'kabupatenkota'=> 'KABUPATEN ACEH BESAR', 'objectprovinsifk'=> 11],
            ['id'=> 1109, 'kabupatenkota'=> 'KABUPATEN PIDIE', 'objectprovinsifk'=> 11],
            ['id'=> 1110, 'kabupatenkota'=> 'KABUPATEN BIREUEN', 'objectprovinsifk'=> 11],
            ['id'=> 1111, 'kabupatenkota'=> 'KABUPATEN ACEH UTARA', 'objectprovinsifk'=> 11],
            ['id'=> 1112, 'kabupatenkota'=> 'KABUPATEN ACEH BARAT DAYA', 'objectprovinsifk'=> 11],
            ['id'=> 1113, 'kabupatenkota'=> 'KABUPATEN GAYO LUES', 'objectprovinsifk'=> 11],
            ['id'=> 1114, 'kabupatenkota'=> 'KABUPATEN ACEH TAMIANG', 'objectprovinsifk'=> 11],
            ['id'=> 1115, 'kabupatenkota'=> 'KABUPATEN NAGAN RAYA', 'objectprovinsifk'=> 11],
            ['id'=> 1116, 'kabupatenkota'=> 'KABUPATEN ACEH JAYA', 'objectprovinsifk'=> 11],
            ['id'=> 1117, 'kabupatenkota'=> 'KABUPATEN BENER MERIAH', 'objectprovinsifk'=> 11],
            ['id'=> 1118, 'kabupatenkota'=> 'KABUPATEN PIDIE JAYA', 'objectprovinsifk'=> 11],
            ['id'=> 1171, 'kabupatenkota'=> 'KOTA BANDA ACEH', 'objectprovinsifk'=> 11],
            ['id'=> 1172, 'kabupatenkota'=> 'KOTA SABANG', 'objectprovinsifk'=> 11],
            ['id'=> 1173, 'kabupatenkota'=> 'KOTA LANGSA', 'objectprovinsifk'=> 11],
            ['id'=> 1174, 'kabupatenkota'=> 'KOTA LHOKSEUMAWE', 'objectprovinsifk'=> 11],
            ['id'=> 1175, 'kabupatenkota'=> 'KOTA SUBULUSSALAM', 'objectprovinsifk'=> 11],
            ['id'=> 1201, 'kabupatenkota'=> 'KABUPATEN NIAS', 'objectprovinsifk'=> 12],
            ['id'=> 1202, 'kabupatenkota'=> 'KABUPATEN MANDAILING NATAL', 'objectprovinsifk'=> 12],
            ['id'=> 1203, 'kabupatenkota'=> 'KABUPATEN TAPANULI SELATAN', 'objectprovinsifk'=> 12],
            ['id'=> 1204, 'kabupatenkota'=> 'KABUPATEN TAPANULI TENGAH', 'objectprovinsifk'=> 12],
            ['id'=> 1205, 'kabupatenkota'=> 'KABUPATEN TAPANULI UTARA', 'objectprovinsifk'=> 12],
            ['id'=> 1206, 'kabupatenkota'=> 'KABUPATEN TOBA SAMOSIR', 'objectprovinsifk'=> 12],
            ['id'=> 1207, 'kabupatenkota'=> 'KABUPATEN LABUHAN BATU', 'objectprovinsifk'=> 12],
            ['id'=> 1208, 'kabupatenkota'=> 'KABUPATEN ASAHAN', 'objectprovinsifk'=> 12],
            ['id'=> 1209, 'kabupatenkota'=> 'KABUPATEN SIMALUNGUN', 'objectprovinsifk'=> 12],
            ['id'=> 1210, 'kabupatenkota'=> 'KABUPATEN DAIRI', 'objectprovinsifk'=> 12],
            ['id'=> 1211, 'kabupatenkota'=> 'KABUPATEN KARO', 'objectprovinsifk'=> 12],
            ['id'=> 1212, 'kabupatenkota'=> 'KABUPATEN DELI SERDANG', 'objectprovinsifk'=> 12],
            ['id'=> 1213, 'kabupatenkota'=> 'KABUPATEN LANGKAT', 'objectprovinsifk'=> 12],
            ['id'=> 1214, 'kabupatenkota'=> 'KABUPATEN NIAS SELATAN', 'objectprovinsifk'=> 12],
            ['id'=> 1215, 'kabupatenkota'=> 'KABUPATEN HUMBANG HASUNDUTAN', 'objectprovinsifk'=> 12],
            ['id'=> 1216, 'kabupatenkota'=> 'KABUPATEN PAKPAK BHARAT', 'objectprovinsifk'=> 12],
            ['id'=> 1217, 'kabupatenkota'=> 'KABUPATEN SAMOSIR', 'objectprovinsifk'=> 12],
            ['id'=> 1218, 'kabupatenkota'=> 'KABUPATEN SERDANG BEDAGAI', 'objectprovinsifk'=> 12],
            ['id'=> 1219, 'kabupatenkota'=> 'KABUPATEN BATU BARA', 'objectprovinsifk'=> 12],
            ['id'=> 1220, 'kabupatenkota'=> 'KABUPATEN PADANG LAWAS UTARA', 'objectprovinsifk'=> 12],
            ['id'=> 1221, 'kabupatenkota'=> 'KABUPATEN PADANG LAWAS', 'objectprovinsifk'=> 12],
            ['id'=> 1222, 'kabupatenkota'=> 'KABUPATEN LABUHAN BATU SELATAN', 'objectprovinsifk'=> 12],
            ['id'=> 1223, 'kabupatenkota'=> 'KABUPATEN LABUHAN BATU UTARA', 'objectprovinsifk'=> 12],
            ['id'=> 1224, 'kabupatenkota'=> 'KABUPATEN NIAS UTARA', 'objectprovinsifk'=> 12],
            ['id'=> 1225, 'kabupatenkota'=> 'KABUPATEN NIAS BARAT', 'objectprovinsifk'=> 12],
            ['id'=> 1271, 'kabupatenkota'=> 'KOTA SIBOLGA', 'objectprovinsifk'=> 12],
            ['id'=> 1272, 'kabupatenkota'=> 'KOTA TANJUNG BALAI', 'objectprovinsifk'=> 12],
            ['id'=> 1273, 'kabupatenkota'=> 'KOTA PEMATANG SIANTAR', 'objectprovinsifk'=> 12],
            ['id'=> 1274, 'kabupatenkota'=> 'KOTA TEBING TINGGI', 'objectprovinsifk'=> 12],
            ['id'=> 1275, 'kabupatenkota'=> 'KOTA MEDAN', 'objectprovinsifk'=> 12],
            ['id'=> 1276, 'kabupatenkota'=> 'KOTA BINJAI', 'objectprovinsifk'=> 12],
            ['id'=> 1277, 'kabupatenkota'=> 'KOTA PADANGSIDIMPUAN', 'objectprovinsifk'=> 12],
            ['id'=> 1278, 'kabupatenkota'=> 'KOTA GUNUNGSITOLI', 'objectprovinsifk'=> 12],
            ['id'=> 1301, 'kabupatenkota'=> 'KABUPATEN KEPULAUAN MENTAWAI', 'objectprovinsifk'=> 13],
            ['id'=> 1302, 'kabupatenkota'=> 'KABUPATEN PESISIR SELATAN', 'objectprovinsifk'=> 13],
            ['id'=> 1303, 'kabupatenkota'=> 'KABUPATEN SOLOK', 'objectprovinsifk'=> 13],
            ['id'=> 1304, 'kabupatenkota'=> 'KABUPATEN SIJUNJUNG', 'objectprovinsifk'=> 13],
            ['id'=> 1305, 'kabupatenkota'=> 'KABUPATEN TANAH DATAR', 'objectprovinsifk'=> 13],
            ['id'=> 1306, 'kabupatenkota'=> 'KABUPATEN PADANG PARIAMAN', 'objectprovinsifk'=> 13],
            ['id'=> 1307, 'kabupatenkota'=> 'KABUPATEN AGAM', 'objectprovinsifk'=> 13],
            ['id'=> 1308, 'kabupatenkota'=> 'KABUPATEN LIMA PULUH KOTA', 'objectprovinsifk'=> 13],
            ['id'=> 1309, 'kabupatenkota'=> 'KABUPATEN PASAMAN', 'objectprovinsifk'=> 13],
            ['id'=> 1310, 'kabupatenkota'=> 'KABUPATEN SOLOK SELATAN', 'objectprovinsifk'=> 13],
            ['id'=> 1311, 'kabupatenkota'=> 'KABUPATEN DHARMASRAYA', 'objectprovinsifk'=> 13],
            ['id'=> 1312, 'kabupatenkota'=> 'KABUPATEN PASAMAN BARAT', 'objectprovinsifk'=> 13],
            ['id'=> 1371, 'kabupatenkota'=> 'KOTA PADANG', 'objectprovinsifk'=> 13],
            ['id'=> 1372, 'kabupatenkota'=> 'KOTA SOLOK', 'objectprovinsifk'=> 13],
            ['id'=> 1373, 'kabupatenkota'=> 'KOTA SAWAH LUNTO', 'objectprovinsifk'=> 13],
            ['id'=> 1374, 'kabupatenkota'=> 'KOTA PADANG PANJANG', 'objectprovinsifk'=> 13],
            ['id'=> 1375, 'kabupatenkota'=> 'KOTA BUKITTINGGI', 'objectprovinsifk'=> 13],
            ['id'=> 1376, 'kabupatenkota'=> 'KOTA PAYAKUMBUH', 'objectprovinsifk'=> 13],
            ['id'=> 1377, 'kabupatenkota'=> 'KOTA PARIAMAN', 'objectprovinsifk'=> 13],
            ['id'=> 1401, 'kabupatenkota'=> 'KABUPATEN KUANTAN SINGINGI', 'objectprovinsifk'=> 14],
            ['id'=> 1402, 'kabupatenkota'=> 'KABUPATEN INDRAGIRI HULU', 'objectprovinsifk'=> 14],
            ['id'=> 1403, 'kabupatenkota'=> 'KABUPATEN INDRAGIRI HILIR', 'objectprovinsifk'=> 14],
            ['id'=> 1404, 'kabupatenkota'=> 'KABUPATEN PELALAWAN', 'objectprovinsifk'=> 14],
            ['id'=> 1405, 'kabupatenkota'=> 'KABUPATEN S I A K', 'objectprovinsifk'=> 14],
            ['id'=> 1406, 'kabupatenkota'=> 'KABUPATEN KAMPAR', 'objectprovinsifk'=> 14],
            ['id'=> 1407, 'kabupatenkota'=> 'KABUPATEN ROKAN HULU', 'objectprovinsifk'=> 14],
            ['id'=> 1408, 'kabupatenkota'=> 'KABUPATEN BENGKALIS', 'objectprovinsifk'=> 14],
            ['id'=> 1409, 'kabupatenkota'=> 'KABUPATEN ROKAN HILIR', 'objectprovinsifk'=> 14],
            ['id'=> 1410, 'kabupatenkota'=> 'KABUPATEN KEPULAUAN MERANTI', 'objectprovinsifk'=> 14],
            ['id'=> 1471, 'kabupatenkota'=> 'KOTA PEKANBARU', 'objectprovinsifk'=> 14],
            ['id'=> 1473, 'kabupatenkota'=> 'KOTA D U M A I', 'objectprovinsifk'=> 14],
            ['id'=> 1501, 'kabupatenkota'=> 'KABUPATEN KERINCI', 'objectprovinsifk'=> 15],
            ['id'=> 1502, 'kabupatenkota'=> 'KABUPATEN MERANGIN', 'objectprovinsifk'=> 15],
            ['id'=> 1503, 'kabupatenkota'=> 'KABUPATEN SAROLANGUN', 'objectprovinsifk'=> 15],
            ['id'=> 1504, 'kabupatenkota'=> 'KABUPATEN BATANG HARI', 'objectprovinsifk'=> 15],
            ['id'=> 1505, 'kabupatenkota'=> 'KABUPATEN MUARO JAMBI', 'objectprovinsifk'=> 15],
            ['id'=> 1506, 'kabupatenkota'=> 'KABUPATEN TANJUNG JABUNG TIMUR', 'objectprovinsifk'=> 15],
            ['id'=> 1507, 'kabupatenkota'=> 'KABUPATEN TANJUNG JABUNG BARAT', 'objectprovinsifk'=> 15],
            ['id'=> 1508, 'kabupatenkota'=> 'KABUPATEN TEBO', 'objectprovinsifk'=> 15],
            ['id'=> 1509, 'kabupatenkota'=> 'KABUPATEN BUNGO', 'objectprovinsifk'=> 15],
            ['id'=> 1571, 'kabupatenkota'=> 'KOTA JAMBI', 'objectprovinsifk'=> 15],
            ['id'=> 1572, 'kabupatenkota'=> 'KOTA SUNGAI PENUH', 'objectprovinsifk'=> 15],
            ['id'=> 1601, 'kabupatenkota'=> 'KABUPATEN OGAN KOMERING ULU', 'objectprovinsifk'=> 16],
            ['id'=> 1602, 'kabupatenkota'=> 'KABUPATEN OGAN KOMERING ILIR', 'objectprovinsifk'=> 16],
            ['id'=> 1603, 'kabupatenkota'=> 'KABUPATEN MUARA ENIM', 'objectprovinsifk'=> 16],
            ['id'=> 1604, 'kabupatenkota'=> 'KABUPATEN LAHAT', 'objectprovinsifk'=> 16],
            ['id'=> 1605, 'kabupatenkota'=> 'KABUPATEN MUSI RAWAS', 'objectprovinsifk'=> 16],
            ['id'=> 1606, 'kabupatenkota'=> 'KABUPATEN MUSI BANYUASIN', 'objectprovinsifk'=> 16],
            ['id'=> 1607, 'kabupatenkota'=> 'KABUPATEN BANYU ASIN', 'objectprovinsifk'=> 16],
            ['id'=> 1608, 'kabupatenkota'=> 'KABUPATEN OGAN KOMERING ULU SELATAN', 'objectprovinsifk'=> 16],
            ['id'=> 1609, 'kabupatenkota'=> 'KABUPATEN OGAN KOMERING ULU TIMUR', 'objectprovinsifk'=> 16],
            ['id'=> 1610, 'kabupatenkota'=> 'KABUPATEN OGAN ILIR', 'objectprovinsifk'=> 16],
            ['id'=> 1611, 'kabupatenkota'=> 'KABUPATEN EMPAT LAWANG', 'objectprovinsifk'=> 16],
            ['id'=> 1612, 'kabupatenkota'=> 'KABUPATEN PENUKAL ABAB LEMATANG ILIR', 'objectprovinsifk'=> 16],
            ['id'=> 1613, 'kabupatenkota'=> 'KABUPATEN MUSI RAWAS UTARA', 'objectprovinsifk'=> 16],
            ['id'=> 1671, 'kabupatenkota'=> 'KOTA PALEMBANG', 'objectprovinsifk'=> 16],
            ['id'=> 1672, 'kabupatenkota'=> 'KOTA PRABUMULIH', 'objectprovinsifk'=> 16],
            ['id'=> 1673, 'kabupatenkota'=> 'KOTA PAGAR ALAM', 'objectprovinsifk'=> 16],
            ['id'=> 1674, 'kabupatenkota'=> 'KOTA LUBUKLINGGAU', 'objectprovinsifk'=> 16],
            ['id'=> 1701, 'kabupatenkota'=> 'KABUPATEN BENGKULU SELATAN', 'objectprovinsifk'=> 17],
            ['id'=> 1702, 'kabupatenkota'=> 'KABUPATEN REJANG LEBONG', 'objectprovinsifk'=> 17],
            ['id'=> 1703, 'kabupatenkota'=> 'KABUPATEN BENGKULU UTARA', 'objectprovinsifk'=> 17],
            ['id'=> 1704, 'kabupatenkota'=> 'KABUPATEN KAUR', 'objectprovinsifk'=> 17],
            ['id'=> 1705, 'kabupatenkota'=> 'KABUPATEN SELUMA', 'objectprovinsifk'=> 17],
            ['id'=> 1706, 'kabupatenkota'=> 'KABUPATEN MUKOMUKO', 'objectprovinsifk'=> 17],
            ['id'=> 1707, 'kabupatenkota'=> 'KABUPATEN LEBONG', 'objectprovinsifk'=> 17],
            ['id'=> 1708, 'kabupatenkota'=> 'KABUPATEN KEPAHIANG', 'objectprovinsifk'=> 17],
            ['id'=> 1709, 'kabupatenkota'=> 'KABUPATEN BENGKULU TENGAH', 'objectprovinsifk'=> 17],
            ['id'=> 1771, 'kabupatenkota'=> 'KOTA BENGKULU', 'objectprovinsifk'=> 17],
            ['id'=> 1801, 'kabupatenkota'=> 'KABUPATEN LAMPUNG BARAT', 'objectprovinsifk'=> 18],
            ['id'=> 1802, 'kabupatenkota'=> 'KABUPATEN TANGGAMUS', 'objectprovinsifk'=> 18],
            ['id'=> 1803, 'kabupatenkota'=> 'KABUPATEN LAMPUNG SELATAN', 'objectprovinsifk'=> 18],
            ['id'=> 1804, 'kabupatenkota'=> 'KABUPATEN LAMPUNG TIMUR', 'objectprovinsifk'=> 18],
            ['id'=> 1805, 'kabupatenkota'=> 'KABUPATEN LAMPUNG TENGAH', 'objectprovinsifk'=> 18],
            ['id'=> 1806, 'kabupatenkota'=> 'KABUPATEN LAMPUNG UTARA', 'objectprovinsifk'=> 18],
            ['id'=> 1807, 'kabupatenkota'=> 'KABUPATEN WAY KANAN', 'objectprovinsifk'=> 18],
            ['id'=> 1808, 'kabupatenkota'=> 'KABUPATEN TULANGBAWANG', 'objectprovinsifk'=> 18],
            ['id'=> 1809, 'kabupatenkota'=> 'KABUPATEN PESAWARAN', 'objectprovinsifk'=> 18],
            ['id'=> 1810, 'kabupatenkota'=> 'KABUPATEN PRINGSEWU', 'objectprovinsifk'=> 18],
            ['id'=> 1811, 'kabupatenkota'=> 'KABUPATEN MESUJI', 'objectprovinsifk'=> 18],
            ['id'=> 1812, 'kabupatenkota'=> 'KABUPATEN TULANG BAWANG BARAT', 'objectprovinsifk'=> 18],
            ['id'=> 1813, 'kabupatenkota'=> 'KABUPATEN PESISIR BARAT', 'objectprovinsifk'=> 18],
            ['id'=> 1871, 'kabupatenkota'=> 'KOTA BANDAR LAMPUNG', 'objectprovinsifk'=> 18],
            ['id'=> 1872, 'kabupatenkota'=> 'KOTA METRO', 'objectprovinsifk'=> 18],
            ['id'=> 1901, 'kabupatenkota'=> 'KABUPATEN BANGKA', 'objectprovinsifk'=> 19],
            ['id'=> 1902, 'kabupatenkota'=> 'KABUPATEN BELITUNG', 'objectprovinsifk'=> 19],
            ['id'=> 1903, 'kabupatenkota'=> 'KABUPATEN BANGKA BARAT', 'objectprovinsifk'=> 19],
            ['id'=> 1904, 'kabupatenkota'=> 'KABUPATEN BANGKA TENGAH', 'objectprovinsifk'=> 19],
            ['id'=> 1905, 'kabupatenkota'=> 'KABUPATEN BANGKA SELATAN', 'objectprovinsifk'=> 19],
            ['id'=> 1906, 'kabupatenkota'=> 'KABUPATEN BELITUNG TIMUR', 'objectprovinsifk'=> 19],
            ['id'=> 1971, 'kabupatenkota'=> 'KOTA PANGKAL PINANG', 'objectprovinsifk'=> 19],
            ['id'=> 2101, 'kabupatenkota'=> 'KABUPATEN KARIMUN', 'objectprovinsifk'=> 21],
            ['id'=> 2102, 'kabupatenkota'=> 'KABUPATEN BINTAN', 'objectprovinsifk'=> 21],
            ['id'=> 2103, 'kabupatenkota'=> 'KABUPATEN NATUNA', 'objectprovinsifk'=> 21],
            ['id'=> 2104, 'kabupatenkota'=> 'KABUPATEN LINGGA', 'objectprovinsifk'=> 21],
            ['id'=> 2105, 'kabupatenkota'=> 'KABUPATEN KEPULAUAN ANAMBAS', 'objectprovinsifk'=> 21],
            ['id'=> 2171, 'kabupatenkota'=> 'KOTA B A T A M', 'objectprovinsifk'=> 21],
            ['id'=> 2172, 'kabupatenkota'=> 'KOTA TANJUNG PINANG', 'objectprovinsifk'=> 21],
            ['id'=> 3101, 'kabupatenkota'=> 'KABUPATEN KEPULAUAN SERIBU', 'objectprovinsifk'=> 31],
            ['id'=> 3171, 'kabupatenkota'=> 'KOTA JAKARTA SELATAN', 'objectprovinsifk'=> 31],
            ['id'=> 3172, 'kabupatenkota'=> 'KOTA JAKARTA TIMUR', 'objectprovinsifk'=> 31],
            ['id'=> 3173, 'kabupatenkota'=> 'KOTA JAKARTA PUSAT', 'objectprovinsifk'=> 31],
            ['id'=> 3174, 'kabupatenkota'=> 'KOTA JAKARTA BARAT', 'objectprovinsifk'=> 31],
            ['id'=> 3175, 'kabupatenkota'=> 'KOTA JAKARTA UTARA', 'objectprovinsifk'=> 31],
            ['id'=> 3201, 'kabupatenkota'=> 'KABUPATEN BOGOR', 'objectprovinsifk'=> 32],
            ['id'=> 3202, 'kabupatenkota'=> 'KABUPATEN SUKABUMI', 'objectprovinsifk'=> 32],
            ['id'=> 3203, 'kabupatenkota'=> 'KABUPATEN CIANJUR', 'objectprovinsifk'=> 32],
            ['id'=> 3204, 'kabupatenkota'=> 'KABUPATEN BANDUNG', 'objectprovinsifk'=> 32],
            ['id'=> 3205, 'kabupatenkota'=> 'KABUPATEN GARUT', 'objectprovinsifk'=> 32],
            ['id'=> 3206, 'kabupatenkota'=> 'KABUPATEN TASIKMALAYA', 'objectprovinsifk'=> 32],
            ['id'=> 3207, 'kabupatenkota'=> 'KABUPATEN CIAMIS', 'objectprovinsifk'=> 32],
            ['id'=> 3208, 'kabupatenkota'=> 'KABUPATEN KUNINGAN', 'objectprovinsifk'=> 32],
            ['id'=> 3209, 'kabupatenkota'=> 'KABUPATEN CIREBON', 'objectprovinsifk'=> 32],
            ['id'=> 3210, 'kabupatenkota'=> 'KABUPATEN MAJALENGKA', 'objectprovinsifk'=> 32],
            ['id'=> 3211, 'kabupatenkota'=> 'KABUPATEN SUMEDANG', 'objectprovinsifk'=> 32],
            ['id'=> 3212, 'kabupatenkota'=> 'KABUPATEN INDRAMAYU', 'objectprovinsifk'=> 32],
            ['id'=> 3213, 'kabupatenkota'=> 'KABUPATEN SUBANG', 'objectprovinsifk'=> 32],
            ['id'=> 3214, 'kabupatenkota'=> 'KABUPATEN PURWAKARTA', 'objectprovinsifk'=> 32],
            ['id'=> 3215, 'kabupatenkota'=> 'KABUPATEN KARAWANG', 'objectprovinsifk'=> 32],
            ['id'=> 3216, 'kabupatenkota'=> 'KABUPATEN BEKASI', 'objectprovinsifk'=> 32],
            ['id'=> 3217, 'kabupatenkota'=> 'KABUPATEN BANDUNG BARAT', 'objectprovinsifk'=> 32],
            ['id'=> 3218, 'kabupatenkota'=> 'KABUPATEN PANGANDARAN', 'objectprovinsifk'=> 32],
            ['id'=> 3271, 'kabupatenkota'=> 'KOTA BOGOR', 'objectprovinsifk'=> 32],
            ['id'=> 3272, 'kabupatenkota'=> 'KOTA SUKABUMI', 'objectprovinsifk'=> 32],
            ['id'=> 3273, 'kabupatenkota'=> 'KOTA BANDUNG', 'objectprovinsifk'=> 32],
            ['id'=> 3274, 'kabupatenkota'=> 'KOTA CIREBON', 'objectprovinsifk'=> 32],
            ['id'=> 3275, 'kabupatenkota'=> 'KOTA BEKASI', 'objectprovinsifk'=> 32],
            ['id'=> 3276, 'kabupatenkota'=> 'KOTA DEPOK', 'objectprovinsifk'=> 32],
            ['id'=> 3277, 'kabupatenkota'=> 'KOTA CIMAHI', 'objectprovinsifk'=> 32],
            ['id'=> 3278, 'kabupatenkota'=> 'KOTA TASIKMALAYA', 'objectprovinsifk'=> 32],
            ['id'=> 3279, 'kabupatenkota'=> 'KOTA BANJAR', 'objectprovinsifk'=> 32],
            ['id'=> 3301, 'kabupatenkota'=> 'KABUPATEN CILACAP', 'objectprovinsifk'=> 33],
            ['id'=> 3302, 'kabupatenkota'=> 'KABUPATEN BANYUMAS', 'objectprovinsifk'=> 33],
            ['id'=> 3303, 'kabupatenkota'=> 'KABUPATEN PURBALINGGA', 'objectprovinsifk'=> 33],
            ['id'=> 3304, 'kabupatenkota'=> 'KABUPATEN BANJARNEGARA', 'objectprovinsifk'=> 33],
            ['id'=> 3305, 'kabupatenkota'=> 'KABUPATEN KEBUMEN', 'objectprovinsifk'=> 33],
            ['id'=> 3306, 'kabupatenkota'=> 'KABUPATEN PURWOREJO', 'objectprovinsifk'=> 33],
            ['id'=> 3307, 'kabupatenkota'=> 'KABUPATEN WONOSOBO', 'objectprovinsifk'=> 33],
            ['id'=> 3308, 'kabupatenkota'=> 'KABUPATEN MAGELANG', 'objectprovinsifk'=> 33],
            ['id'=> 3309, 'kabupatenkota'=> 'KABUPATEN BOYOLALI', 'objectprovinsifk'=> 33],
            ['id'=> 3310, 'kabupatenkota'=> 'KABUPATEN KLATEN', 'objectprovinsifk'=> 33],
            ['id'=> 3311, 'kabupatenkota'=> 'KABUPATEN SUKOHARJO', 'objectprovinsifk'=> 33],
            ['id'=> 3312, 'kabupatenkota'=> 'KABUPATEN WONOGIRI', 'objectprovinsifk'=> 33],
            ['id'=> 3313, 'kabupatenkota'=> 'KABUPATEN KARANGANYAR', 'objectprovinsifk'=> 33],
            ['id'=> 3314, 'kabupatenkota'=> 'KABUPATEN SRAGEN', 'objectprovinsifk'=> 33],
            ['id'=> 3315, 'kabupatenkota'=> 'KABUPATEN GROBOGAN', 'objectprovinsifk'=> 33],
            ['id'=> 3316, 'kabupatenkota'=> 'KABUPATEN BLORA', 'objectprovinsifk'=> 33],
            ['id'=> 3317, 'kabupatenkota'=> 'KABUPATEN REMBANG', 'objectprovinsifk'=> 33],
            ['id'=> 3318, 'kabupatenkota'=> 'KABUPATEN PATI', 'objectprovinsifk'=> 33],
            ['id'=> 3319, 'kabupatenkota'=> 'KABUPATEN KUDUS', 'objectprovinsifk'=> 33],
            ['id'=> 3320, 'kabupatenkota'=> 'KABUPATEN JEPARA', 'objectprovinsifk'=> 33],
            ['id'=> 3321, 'kabupatenkota'=> 'KABUPATEN DEMAK', 'objectprovinsifk'=> 33],
            ['id'=> 3322, 'kabupatenkota'=> 'KABUPATEN SEMARANG', 'objectprovinsifk'=> 33],
            ['id'=> 3323, 'kabupatenkota'=> 'KABUPATEN TEMANGGUNG', 'objectprovinsifk'=> 33],
            ['id'=> 3324, 'kabupatenkota'=> 'KABUPATEN KENDAL', 'objectprovinsifk'=> 33],
            ['id'=> 3325, 'kabupatenkota'=> 'KABUPATEN BATANG', 'objectprovinsifk'=> 33],
            ['id'=> 3326, 'kabupatenkota'=> 'KABUPATEN PEKALONGAN', 'objectprovinsifk'=> 33],
            ['id'=> 3327, 'kabupatenkota'=> 'KABUPATEN PEMALANG', 'objectprovinsifk'=> 33],
            ['id'=> 3328, 'kabupatenkota'=> 'KABUPATEN TEGAL', 'objectprovinsifk'=> 33],
            ['id'=> 3329, 'kabupatenkota'=> 'KABUPATEN BREBES', 'objectprovinsifk'=> 33],
            ['id'=> 3371, 'kabupatenkota'=> 'KOTA MAGELANG', 'objectprovinsifk'=> 33],
            ['id'=> 3372, 'kabupatenkota'=> 'KOTA SURAKARTA', 'objectprovinsifk'=> 33],
            ['id'=> 3373, 'kabupatenkota'=> 'KOTA SALATIGA', 'objectprovinsifk'=> 33],
            ['id'=> 3374, 'kabupatenkota'=> 'KOTA SEMARANG', 'objectprovinsifk'=> 33],
            ['id'=> 3375, 'kabupatenkota'=> 'KOTA PEKALONGAN', 'objectprovinsifk'=> 33],
            ['id'=> 3376, 'kabupatenkota'=> 'KOTA TEGAL', 'objectprovinsifk'=> 33],
            ['id'=> 3401, 'kabupatenkota'=> 'KABUPATEN KULON PROGO', 'objectprovinsifk'=> 34],
            ['id'=> 3402, 'kabupatenkota'=> 'KABUPATEN BANTUL', 'objectprovinsifk'=> 34],
            ['id'=> 3403, 'kabupatenkota'=> 'KABUPATEN GUNUNG KIDUL', 'objectprovinsifk'=> 34],
            ['id'=> 3404, 'kabupatenkota'=> 'KABUPATEN SLEMAN', 'objectprovinsifk'=> 34],
            ['id'=> 3471, 'kabupatenkota'=> 'KOTA YOGYAKARTA', 'objectprovinsifk'=> 34],
            ['id'=> 3501, 'kabupatenkota'=> 'KABUPATEN PACITAN', 'objectprovinsifk'=> 35],
            ['id'=> 3502, 'kabupatenkota'=> 'KABUPATEN PONOROGO', 'objectprovinsifk'=> 35],
            ['id'=> 3503, 'kabupatenkota'=> 'KABUPATEN TRENGGALEK', 'objectprovinsifk'=> 35],
            ['id'=> 3504, 'kabupatenkota'=> 'KABUPATEN TULUNGAGUNG', 'objectprovinsifk'=> 35],
            ['id'=> 3505, 'kabupatenkota'=> 'KABUPATEN BLITAR', 'objectprovinsifk'=> 35],
            ['id'=> 3506, 'kabupatenkota'=> 'KABUPATEN KEDIRI', 'objectprovinsifk'=> 35],
            ['id'=> 3507, 'kabupatenkota'=> 'KABUPATEN MALANG', 'objectprovinsifk'=> 35],
            ['id'=> 3508, 'kabupatenkota'=> 'KABUPATEN LUMAJANG', 'objectprovinsifk'=> 35],
            ['id'=> 3509, 'kabupatenkota'=> 'KABUPATEN JEMBER', 'objectprovinsifk'=> 35],
            ['id'=> 3510, 'kabupatenkota'=> 'KABUPATEN BANYUWANGI', 'objectprovinsifk'=> 35],
            ['id'=> 3511, 'kabupatenkota'=> 'KABUPATEN BONDOWOSO', 'objectprovinsifk'=> 35],
            ['id'=> 3512, 'kabupatenkota'=> 'KABUPATEN SITUBONDO', 'objectprovinsifk'=> 35],
            ['id'=> 3513, 'kabupatenkota'=> 'KABUPATEN PROBOLINGGO', 'objectprovinsifk'=> 35],
            ['id'=> 3514, 'kabupatenkota'=> 'KABUPATEN PASURUAN', 'objectprovinsifk'=> 35],
            ['id'=> 3515, 'kabupatenkota'=> 'KABUPATEN SIDOARJO', 'objectprovinsifk'=> 35],
            ['id'=> 3516, 'kabupatenkota'=> 'KABUPATEN MOJOKERTO', 'objectprovinsifk'=> 35],
            ['id'=> 3517, 'kabupatenkota'=> 'KABUPATEN JOMBANG', 'objectprovinsifk'=> 35],
            ['id'=> 3518, 'kabupatenkota'=> 'KABUPATEN NGANJUK', 'objectprovinsifk'=> 35],
            ['id'=> 3519, 'kabupatenkota'=> 'KABUPATEN MADIUN', 'objectprovinsifk'=> 35],
            ['id'=> 3520, 'kabupatenkota'=> 'KABUPATEN MAGETAN', 'objectprovinsifk'=> 35],
            ['id'=> 3521, 'kabupatenkota'=> 'KABUPATEN NGAWI', 'objectprovinsifk'=> 35],
            ['id'=> 3522, 'kabupatenkota'=> 'KABUPATEN BOJONEGORO', 'objectprovinsifk'=> 35],
            ['id'=> 3523, 'kabupatenkota'=> 'KABUPATEN TUBAN', 'objectprovinsifk'=> 35],
            ['id'=> 3524, 'kabupatenkota'=> 'KABUPATEN LAMONGAN', 'objectprovinsifk'=> 35],
            ['id'=> 3525, 'kabupatenkota'=> 'KABUPATEN GRESIK', 'objectprovinsifk'=> 35],
            ['id'=> 3526, 'kabupatenkota'=> 'KABUPATEN BANGKALAN', 'objectprovinsifk'=> 35],
            ['id'=> 3527, 'kabupatenkota'=> 'KABUPATEN SAMPANG', 'objectprovinsifk'=> 35],
            ['id'=> 3528, 'kabupatenkota'=> 'KABUPATEN PAMEKASAN', 'objectprovinsifk'=> 35],
            ['id'=> 3529, 'kabupatenkota'=> 'KABUPATEN SUMENEP', 'objectprovinsifk'=> 35],
            ['id'=> 3571, 'kabupatenkota'=> 'KOTA KEDIRI', 'objectprovinsifk'=> 35],
            ['id'=> 3572, 'kabupatenkota'=> 'KOTA BLITAR', 'objectprovinsifk'=> 35],
            ['id'=> 3573, 'kabupatenkota'=> 'KOTA MALANG', 'objectprovinsifk'=> 35],
            ['id'=> 3574, 'kabupatenkota'=> 'KOTA PROBOLINGGO', 'objectprovinsifk'=> 35],
            ['id'=> 3575, 'kabupatenkota'=> 'KOTA PASURUAN', 'objectprovinsifk'=> 35],
            ['id'=> 3576, 'kabupatenkota'=> 'KOTA MOJOKERTO', 'objectprovinsifk'=> 35],
            ['id'=> 3577, 'kabupatenkota'=> 'KOTA MADIUN', 'objectprovinsifk'=> 35],
            ['id'=> 3578, 'kabupatenkota'=> 'KOTA SURABAYA', 'objectprovinsifk'=> 35],
            ['id'=> 3579, 'kabupatenkota'=> 'KOTA BATU', 'objectprovinsifk'=> 35],
            ['id'=> 3601, 'kabupatenkota'=> 'KABUPATEN PANDEGLANG', 'objectprovinsifk'=> 36],
            ['id'=> 3602, 'kabupatenkota'=> 'KABUPATEN LEBAK', 'objectprovinsifk'=> 36],
            ['id'=> 3603, 'kabupatenkota'=> 'KABUPATEN TANGERANG', 'objectprovinsifk'=> 36],
            ['id'=> 3604, 'kabupatenkota'=> 'KABUPATEN SERANG', 'objectprovinsifk'=> 36],
            ['id'=> 3671, 'kabupatenkota'=> 'KOTA TANGERANG', 'objectprovinsifk'=> 36],
            ['id'=> 3672, 'kabupatenkota'=> 'KOTA CILEGON', 'objectprovinsifk'=> 36],
            ['id'=> 3673, 'kabupatenkota'=> 'KOTA SERANG', 'objectprovinsifk'=> 36],
            ['id'=> 3674, 'kabupatenkota'=> 'KOTA TANGERANG SELATAN', 'objectprovinsifk'=> 36],
            ['id'=> 5101, 'kabupatenkota'=> 'KABUPATEN JEMBRANA', 'objectprovinsifk'=> 51],
            ['id'=> 5102, 'kabupatenkota'=> 'KABUPATEN TABANAN', 'objectprovinsifk'=> 51],
            ['id'=> 5103, 'kabupatenkota'=> 'KABUPATEN BADUNG', 'objectprovinsifk'=> 51],
            ['id'=> 5104, 'kabupatenkota'=> 'KABUPATEN GIANYAR', 'objectprovinsifk'=> 51],
            ['id'=> 5105, 'kabupatenkota'=> 'KABUPATEN KLUNGKUNG', 'objectprovinsifk'=> 51],
            ['id'=> 5106, 'kabupatenkota'=> 'KABUPATEN BANGLI', 'objectprovinsifk'=> 51],
            ['id'=> 5107, 'kabupatenkota'=> 'KABUPATEN KARANG ASEM', 'objectprovinsifk'=> 51],
            ['id'=> 5108, 'kabupatenkota'=> 'KABUPATEN BULELENG', 'objectprovinsifk'=> 51],
            ['id'=> 5171, 'kabupatenkota'=> 'KOTA DENPASAR', 'objectprovinsifk'=> 51],
            ['id'=> 5201, 'kabupatenkota'=> 'KABUPATEN LOMBOK BARAT', 'objectprovinsifk'=> 52],
            ['id'=> 5202, 'kabupatenkota'=> 'KABUPATEN LOMBOK TENGAH', 'objectprovinsifk'=> 52],
            ['id'=> 5203, 'kabupatenkota'=> 'KABUPATEN LOMBOK TIMUR', 'objectprovinsifk'=> 52],
            ['id'=> 5204, 'kabupatenkota'=> 'KABUPATEN SUMBAWA', 'objectprovinsifk'=> 52],
            ['id'=> 5205, 'kabupatenkota'=> 'KABUPATEN DOMPU', 'objectprovinsifk'=> 52],
            ['id'=> 5206, 'kabupatenkota'=> 'KABUPATEN BIMA', 'objectprovinsifk'=> 52],
            ['id'=> 5207, 'kabupatenkota'=> 'KABUPATEN SUMBAWA BARAT', 'objectprovinsifk'=> 52],
            ['id'=> 5208, 'kabupatenkota'=> 'KABUPATEN LOMBOK UTARA', 'objectprovinsifk'=> 52],
            ['id'=> 5271, 'kabupatenkota'=> 'KOTA MATARAM', 'objectprovinsifk'=> 52],
            ['id'=> 5272, 'kabupatenkota'=> 'KOTA BIMA', 'objectprovinsifk'=> 52],
            ['id'=> 5301, 'kabupatenkota'=> 'KABUPATEN SUMBA BARAT', 'objectprovinsifk'=> 53],
            ['id'=> 5302, 'kabupatenkota'=> 'KABUPATEN SUMBA TIMUR', 'objectprovinsifk'=> 53],
            ['id'=> 5303, 'kabupatenkota'=> 'KABUPATEN KUPANG', 'objectprovinsifk'=> 53],
            ['id'=> 5304, 'kabupatenkota'=> 'KABUPATEN TIMOR TENGAH SELATAN', 'objectprovinsifk'=> 53],
            ['id'=> 5305, 'kabupatenkota'=> 'KABUPATEN TIMOR TENGAH UTARA', 'objectprovinsifk'=> 53],
            ['id'=> 5306, 'kabupatenkota'=> 'KABUPATEN BELU', 'objectprovinsifk'=> 53],
            ['id'=> 5307, 'kabupatenkota'=> 'KABUPATEN ALOR', 'objectprovinsifk'=> 53],
            ['id'=> 5308, 'kabupatenkota'=> 'KABUPATEN LEMBATA', 'objectprovinsifk'=> 53],
            ['id'=> 5309, 'kabupatenkota'=> 'KABUPATEN FLORES TIMUR', 'objectprovinsifk'=> 53],
            ['id'=> 5310, 'kabupatenkota'=> 'KABUPATEN SIKKA', 'objectprovinsifk'=> 53],
            ['id'=> 5311, 'kabupatenkota'=> 'KABUPATEN ENDE', 'objectprovinsifk'=> 53],
            ['id'=> 5312, 'kabupatenkota'=> 'KABUPATEN NGADA', 'objectprovinsifk'=> 53],
            ['id'=> 5313, 'kabupatenkota'=> 'KABUPATEN MANGGARAI', 'objectprovinsifk'=> 53],
            ['id'=> 5314, 'kabupatenkota'=> 'KABUPATEN ROTE NDAO', 'objectprovinsifk'=> 53],
            ['id'=> 5315, 'kabupatenkota'=> 'KABUPATEN MANGGARAI BARAT', 'objectprovinsifk'=> 53],
            ['id'=> 5316, 'kabupatenkota'=> 'KABUPATEN SUMBA TENGAH', 'objectprovinsifk'=> 53],
            ['id'=> 5317, 'kabupatenkota'=> 'KABUPATEN SUMBA BARAT DAYA', 'objectprovinsifk'=> 53],
            ['id'=> 5318, 'kabupatenkota'=> 'KABUPATEN NAGEKEO', 'objectprovinsifk'=> 53],
            ['id'=> 5319, 'kabupatenkota'=> 'KABUPATEN MANGGARAI TIMUR', 'objectprovinsifk'=> 53],
            ['id'=> 5320, 'kabupatenkota'=> 'KABUPATEN SABU RAIJUA', 'objectprovinsifk'=> 53],
            ['id'=> 5321, 'kabupatenkota'=> 'KABUPATEN MALAKA', 'objectprovinsifk'=> 53],
            ['id'=> 5371, 'kabupatenkota'=> 'KOTA KUPANG', 'objectprovinsifk'=> 53],
            ['id'=> 6101, 'kabupatenkota'=> 'KABUPATEN SAMBAS', 'objectprovinsifk'=> 61],
            ['id'=> 6102, 'kabupatenkota'=> 'KABUPATEN BENGKAYANG', 'objectprovinsifk'=> 61],
            ['id'=> 6103, 'kabupatenkota'=> 'KABUPATEN LANDAK', 'objectprovinsifk'=> 61],
            ['id'=> 6104, 'kabupatenkota'=> 'KABUPATEN MEMPAWAH', 'objectprovinsifk'=> 61],
            ['id'=> 6105, 'kabupatenkota'=> 'KABUPATEN SANGGAU', 'objectprovinsifk'=> 61],
            ['id'=> 6106, 'kabupatenkota'=> 'KABUPATEN KETAPANG', 'objectprovinsifk'=> 61],
            ['id'=> 6107, 'kabupatenkota'=> 'KABUPATEN SINTANG', 'objectprovinsifk'=> 61],
            ['id'=> 6108, 'kabupatenkota'=> 'KABUPATEN KAPUAS HULU', 'objectprovinsifk'=> 61],
            ['id'=> 6109, 'kabupatenkota'=> 'KABUPATEN SEKADAU', 'objectprovinsifk'=> 61],
            ['id'=> 6110, 'kabupatenkota'=> 'KABUPATEN MELAWI', 'objectprovinsifk'=> 61],
            ['id'=> 6111, 'kabupatenkota'=> 'KABUPATEN KAYONG UTARA', 'objectprovinsifk'=> 61],
            ['id'=> 6112, 'kabupatenkota'=> 'KABUPATEN KUBU RAYA', 'objectprovinsifk'=> 61],
            ['id'=> 6171, 'kabupatenkota'=> 'KOTA PONTIANAK', 'objectprovinsifk'=> 61],
            ['id'=> 6172, 'kabupatenkota'=> 'KOTA SINGKAWANG', 'objectprovinsifk'=> 61],
            ['id'=> 6201, 'kabupatenkota'=> 'KABUPATEN KOTAWARINGIN BARAT', 'objectprovinsifk'=> 62],
            ['id'=> 6202, 'kabupatenkota'=> 'KABUPATEN KOTAWARINGIN TIMUR', 'objectprovinsifk'=> 62],
            ['id'=> 6203, 'kabupatenkota'=> 'KABUPATEN KAPUAS', 'objectprovinsifk'=> 62],
            ['id'=> 6204, 'kabupatenkota'=> 'KABUPATEN BARITO SELATAN', 'objectprovinsifk'=> 62],
            ['id'=> 6205, 'kabupatenkota'=> 'KABUPATEN BARITO UTARA', 'objectprovinsifk'=> 62],
            ['id'=> 6206, 'kabupatenkota'=> 'KABUPATEN SUKAMARA', 'objectprovinsifk'=> 62],
            ['id'=> 6207, 'kabupatenkota'=> 'KABUPATEN LAMANDAU', 'objectprovinsifk'=> 62],
            ['id'=> 6208, 'kabupatenkota'=> 'KABUPATEN SERUYAN', 'objectprovinsifk'=> 62],
            ['id'=> 6209, 'kabupatenkota'=> 'KABUPATEN KATINGAN', 'objectprovinsifk'=> 62],
            ['id'=> 6210, 'kabupatenkota'=> 'KABUPATEN PULANG PISAU', 'objectprovinsifk'=> 62],
            ['id'=> 6211, 'kabupatenkota'=> 'KABUPATEN GUNUNG MAS', 'objectprovinsifk'=> 62],
            ['id'=> 6212, 'kabupatenkota'=> 'KABUPATEN BARITO TIMUR', 'objectprovinsifk'=> 62],
            ['id'=> 6213, 'kabupatenkota'=> 'KABUPATEN MURUNG RAYA', 'objectprovinsifk'=> 62],
            ['id'=> 6271, 'kabupatenkota'=> 'KOTA PALANGKA RAYA', 'objectprovinsifk'=> 62],
            ['id'=> 6301, 'kabupatenkota'=> 'KABUPATEN TANAH LAUT', 'objectprovinsifk'=> 63],
            ['id'=> 6302, 'kabupatenkota'=> 'KABUPATEN KOTA BARU', 'objectprovinsifk'=> 63],
            ['id'=> 6303, 'kabupatenkota'=> 'KABUPATEN BANJAR', 'objectprovinsifk'=> 63],
            ['id'=> 6304, 'kabupatenkota'=> 'KABUPATEN BARITO KUALA', 'objectprovinsifk'=> 63],
            ['id'=> 6305, 'kabupatenkota'=> 'KABUPATEN TAPIN', 'objectprovinsifk'=> 63],
            ['id'=> 6306, 'kabupatenkota'=> 'KABUPATEN HULU SUNGAI SELATAN', 'objectprovinsifk'=> 63],
            ['id'=> 6307, 'kabupatenkota'=> 'KABUPATEN HULU SUNGAI TENGAH', 'objectprovinsifk'=> 63],
            ['id'=> 6308, 'kabupatenkota'=> 'KABUPATEN HULU SUNGAI UTARA', 'objectprovinsifk'=> 63],
            ['id'=> 6309, 'kabupatenkota'=> 'KABUPATEN TABALONG', 'objectprovinsifk'=> 63],
            ['id'=> 6310, 'kabupatenkota'=> 'KABUPATEN TANAH BUMBU', 'objectprovinsifk'=> 63],
            ['id'=> 6311, 'kabupatenkota'=> 'KABUPATEN BALANGAN', 'objectprovinsifk'=> 63],
            ['id'=> 6371, 'kabupatenkota'=> 'KOTA BANJARMASIN', 'objectprovinsifk'=> 63],
            ['id'=> 6372, 'kabupatenkota'=> 'KOTA BANJAR BARU', 'objectprovinsifk'=> 63],
            ['id'=> 6401, 'kabupatenkota'=> 'KABUPATEN PASER', 'objectprovinsifk'=> 64],
            ['id'=> 6402, 'kabupatenkota'=> 'KABUPATEN KUTAI BARAT', 'objectprovinsifk'=> 64],
            ['id'=> 6403, 'kabupatenkota'=> 'KABUPATEN KUTAI KARTANEGARA', 'objectprovinsifk'=> 64],
            ['id'=> 6404, 'kabupatenkota'=> 'KABUPATEN KUTAI TIMUR', 'objectprovinsifk'=> 64],
            ['id'=> 6405, 'kabupatenkota'=> 'KABUPATEN BERAU', 'objectprovinsifk'=> 64],
            ['id'=> 6409, 'kabupatenkota'=> 'KABUPATEN PENAJAM PASER UTARA', 'objectprovinsifk'=> 64],
            ['id'=> 6411, 'kabupatenkota'=> 'KABUPATEN MAHAKAM HULU', 'objectprovinsifk'=> 64],
            ['id'=> 6471, 'kabupatenkota'=> 'KOTA BALIKPAPAN', 'objectprovinsifk'=> 64],
            ['id'=> 6472, 'kabupatenkota'=> 'KOTA SAMARINDA', 'objectprovinsifk'=> 64],
            ['id'=> 6474, 'kabupatenkota'=> 'KOTA BONTANG', 'objectprovinsifk'=> 64],
            ['id'=> 6501, 'kabupatenkota'=> 'KABUPATEN MALINAU', 'objectprovinsifk'=> 65],
            ['id'=> 6502, 'kabupatenkota'=> 'KABUPATEN BULUNGAN', 'objectprovinsifk'=> 65],
            ['id'=> 6503, 'kabupatenkota'=> 'KABUPATEN TANA TIDUNG', 'objectprovinsifk'=> 65],
            ['id'=> 6504, 'kabupatenkota'=> 'KABUPATEN NUNUKAN', 'objectprovinsifk'=> 65],
            ['id'=> 6571, 'kabupatenkota'=> 'KOTA TARAKAN', 'objectprovinsifk'=> 65],
            ['id'=> 7101, 'kabupatenkota'=> 'KABUPATEN BOLAANG MONGONDOW', 'objectprovinsifk'=> 71],
            ['id'=> 7102, 'kabupatenkota'=> 'KABUPATEN MINAHASA', 'objectprovinsifk'=> 71],
            ['id'=> 7103, 'kabupatenkota'=> 'KABUPATEN KEPULAUAN SANGIHE', 'objectprovinsifk'=> 71],
            ['id'=> 7104, 'kabupatenkota'=> 'KABUPATEN KEPULAUAN TALAUD', 'objectprovinsifk'=> 71],
            ['id'=> 7105, 'kabupatenkota'=> 'KABUPATEN MINAHASA SELATAN', 'objectprovinsifk'=> 71],
            ['id'=> 7106, 'kabupatenkota'=> 'KABUPATEN MINAHASA UTARA', 'objectprovinsifk'=> 71],
            ['id'=> 7107, 'kabupatenkota'=> 'KABUPATEN BOLAANG MONGONDOW UTARA', 'objectprovinsifk'=> 71],
            ['id'=> 7108, 'kabupatenkota'=> 'KABUPATEN SIAU TAGULANDANG BIARO', 'objectprovinsifk'=> 71],
            ['id'=> 7109, 'kabupatenkota'=> 'KABUPATEN MINAHASA TENGGARA', 'objectprovinsifk'=> 71],
            ['id'=> 7110, 'kabupatenkota'=> 'KABUPATEN BOLAANG MONGONDOW SELATAN', 'objectprovinsifk'=> 71],
            ['id'=> 7111, 'kabupatenkota'=> 'KABUPATEN BOLAANG MONGONDOW TIMUR', 'objectprovinsifk'=> 71],
            ['id'=> 7171, 'kabupatenkota'=> 'KOTA MANADO', 'objectprovinsifk'=> 71],
            ['id'=> 7172, 'kabupatenkota'=> 'KOTA BITUNG', 'objectprovinsifk'=> 71],
            ['id'=> 7173, 'kabupatenkota'=> 'KOTA TOMOHON', 'objectprovinsifk'=> 71],
            ['id'=> 7174, 'kabupatenkota'=> 'KOTA KOTAMOBAGU', 'objectprovinsifk'=> 71],
            ['id'=> 7201, 'kabupatenkota'=> 'KABUPATEN BANGGAI KEPULAUAN', 'objectprovinsifk'=> 72],
            ['id'=> 7202, 'kabupatenkota'=> 'KABUPATEN BANGGAI', 'objectprovinsifk'=> 72],
            ['id'=> 7203, 'kabupatenkota'=> 'KABUPATEN MOROWALI', 'objectprovinsifk'=> 72],
            ['id'=> 7204, 'kabupatenkota'=> 'KABUPATEN POSO', 'objectprovinsifk'=> 72],
            ['id'=> 7205, 'kabupatenkota'=> 'KABUPATEN DONGGALA', 'objectprovinsifk'=> 72],
            ['id'=> 7206, 'kabupatenkota'=> 'KABUPATEN TOLI-TOLI', 'objectprovinsifk'=> 72],
            ['id'=> 7207, 'kabupatenkota'=> 'KABUPATEN BUOL', 'objectprovinsifk'=> 72],
            ['id'=> 7208, 'kabupatenkota'=> 'KABUPATEN PARIGI MOUTONG', 'objectprovinsifk'=> 72],
            ['id'=> 7209, 'kabupatenkota'=> 'KABUPATEN TOJO UNA-UNA', 'objectprovinsifk'=> 72],
            ['id'=> 7210, 'kabupatenkota'=> 'KABUPATEN SIGI', 'objectprovinsifk'=> 72],
            ['id'=> 7211, 'kabupatenkota'=> 'KABUPATEN BANGGAI LAUT', 'objectprovinsifk'=> 72],
            ['id'=> 7212, 'kabupatenkota'=> 'KABUPATEN MOROWALI UTARA', 'objectprovinsifk'=> 72],
            ['id'=> 7271, 'kabupatenkota'=> 'KOTA PALU', 'objectprovinsifk'=> 72],
            ['id'=> 7301, 'kabupatenkota'=> 'KABUPATEN KEPULAUAN SELAYAR', 'objectprovinsifk'=> 73],
            ['id'=> 7302, 'kabupatenkota'=> 'KABUPATEN BULUKUMBA', 'objectprovinsifk'=> 73],
            ['id'=> 7303, 'kabupatenkota'=> 'KABUPATEN BANTAENG', 'objectprovinsifk'=> 73],
            ['id'=> 7304, 'kabupatenkota'=> 'KABUPATEN JENEPONTO', 'objectprovinsifk'=> 73],
            ['id'=> 7305, 'kabupatenkota'=> 'KABUPATEN TAKALAR', 'objectprovinsifk'=> 73],
            ['id'=> 7306, 'kabupatenkota'=> 'KABUPATEN GOWA', 'objectprovinsifk'=> 73],
            ['id'=> 7307, 'kabupatenkota'=> 'KABUPATEN SINJAI', 'objectprovinsifk'=> 73],
            ['id'=> 7308, 'kabupatenkota'=> 'KABUPATEN MAROS', 'objectprovinsifk'=> 73],
            ['id'=> 7309, 'kabupatenkota'=> 'KABUPATEN PANGKAJENE DAN KEPULAUAN', 'objectprovinsifk'=> 73],
            ['id'=> 7310, 'kabupatenkota'=> 'KABUPATEN BARRU', 'objectprovinsifk'=> 73],
            ['id'=> 7311, 'kabupatenkota'=> 'KABUPATEN BONE', 'objectprovinsifk'=> 73],
            ['id'=> 7312, 'kabupatenkota'=> 'KABUPATEN SOPPENG', 'objectprovinsifk'=> 73],
            ['id'=> 7313, 'kabupatenkota'=> 'KABUPATEN WAJO', 'objectprovinsifk'=> 73],
            ['id'=> 7314, 'kabupatenkota'=> 'KABUPATEN SIDENRENG RAPPANG', 'objectprovinsifk'=> 73],
            ['id'=> 7315, 'kabupatenkota'=> 'KABUPATEN PINRANG', 'objectprovinsifk'=> 73],
            ['id'=> 7316, 'kabupatenkota'=> 'KABUPATEN ENREKANG', 'objectprovinsifk'=> 73],
            ['id'=> 7317, 'kabupatenkota'=> 'KABUPATEN LUWU', 'objectprovinsifk'=> 73],
            ['id'=> 7318, 'kabupatenkota'=> 'KABUPATEN TANA TORAJA', 'objectprovinsifk'=> 73],
            ['id'=> 7322, 'kabupatenkota'=> 'KABUPATEN LUWU UTARA', 'objectprovinsifk'=> 73],
            ['id'=> 7325, 'kabupatenkota'=> 'KABUPATEN LUWU TIMUR', 'objectprovinsifk'=> 73],
            ['id'=> 7326, 'kabupatenkota'=> 'KABUPATEN TORAJA UTARA', 'objectprovinsifk'=> 73],
            ['id'=> 7371, 'kabupatenkota'=> 'KOTA MAKASSAR', 'objectprovinsifk'=> 73],
            ['id'=> 7372, 'kabupatenkota'=> 'KOTA PAREPARE', 'objectprovinsifk'=> 73],
            ['id'=> 7373, 'kabupatenkota'=> 'KOTA PALOPO', 'objectprovinsifk'=> 73],
            ['id'=> 7401, 'kabupatenkota'=> 'KABUPATEN BUTON', 'objectprovinsifk'=> 74],
            ['id'=> 7402, 'kabupatenkota'=> 'KABUPATEN MUNA', 'objectprovinsifk'=> 74],
            ['id'=> 7403, 'kabupatenkota'=> 'KABUPATEN KONAWE', 'objectprovinsifk'=> 74],
            ['id'=> 7404, 'kabupatenkota'=> 'KABUPATEN KOLAKA', 'objectprovinsifk'=> 74],
            ['id'=> 7405, 'kabupatenkota'=> 'KABUPATEN KONAWE SELATAN', 'objectprovinsifk'=> 74],
            ['id'=> 7406, 'kabupatenkota'=> 'KABUPATEN BOMBANA', 'objectprovinsifk'=> 74],
            ['id'=> 7407, 'kabupatenkota'=> 'KABUPATEN WAKATOBI', 'objectprovinsifk'=> 74],
            ['id'=> 7408, 'kabupatenkota'=> 'KABUPATEN KOLAKA UTARA', 'objectprovinsifk'=> 74],
            ['id'=> 7409, 'kabupatenkota'=> 'KABUPATEN BUTON UTARA', 'objectprovinsifk'=> 74],
            ['id'=> 7410, 'kabupatenkota'=> 'KABUPATEN KONAWE UTARA', 'objectprovinsifk'=> 74],
            ['id'=> 7411, 'kabupatenkota'=> 'KABUPATEN KOLAKA TIMUR', 'objectprovinsifk'=> 74],
            ['id'=> 7412, 'kabupatenkota'=> 'KABUPATEN KONAWE KEPULAUAN', 'objectprovinsifk'=> 74],
            ['id'=> 7413, 'kabupatenkota'=> 'KABUPATEN MUNA BARAT', 'objectprovinsifk'=> 74],
            ['id'=> 7414, 'kabupatenkota'=> 'KABUPATEN BUTON TENGAH', 'objectprovinsifk'=> 74],
            ['id'=> 7415, 'kabupatenkota'=> 'KABUPATEN BUTON SELATAN', 'objectprovinsifk'=> 74],
            ['id'=> 7471, 'kabupatenkota'=> 'KOTA KENDARI', 'objectprovinsifk'=> 74],
            ['id'=> 7472, 'kabupatenkota'=> 'KOTA BAUBAU', 'objectprovinsifk'=> 74],
            ['id'=> 7501, 'kabupatenkota'=> 'KABUPATEN BOALEMO', 'objectprovinsifk'=> 75],
            ['id'=> 7502, 'kabupatenkota'=> 'KABUPATEN GORONTALO', 'objectprovinsifk'=> 75],
            ['id'=> 7503, 'kabupatenkota'=> 'KABUPATEN POHUWATO', 'objectprovinsifk'=> 75],
            ['id'=> 7504, 'kabupatenkota'=> 'KABUPATEN BONE BOLANGO', 'objectprovinsifk'=> 75],
            ['id'=> 7505, 'kabupatenkota'=> 'KABUPATEN GORONTALO UTARA', 'objectprovinsifk'=> 75],
            ['id'=> 7571, 'kabupatenkota'=> 'KOTA GORONTALO', 'objectprovinsifk'=> 75],
            ['id'=> 7601, 'kabupatenkota'=> 'KABUPATEN MAJENE', 'objectprovinsifk'=> 76],
            ['id'=> 7602, 'kabupatenkota'=> 'KABUPATEN POLEWALI MANDAR', 'objectprovinsifk'=> 76],
            ['id'=> 7603, 'kabupatenkota'=> 'KABUPATEN MAMASA', 'objectprovinsifk'=> 76],
            ['id'=> 7604, 'kabupatenkota'=> 'KABUPATEN MAMUJU', 'objectprovinsifk'=> 76],
            ['id'=> 7605, 'kabupatenkota'=> 'KABUPATEN MAMUJU UTARA', 'objectprovinsifk'=> 76],
            ['id'=> 7606, 'kabupatenkota'=> 'KABUPATEN MAMUJU TENGAH', 'objectprovinsifk'=> 76],
            ['id'=> 8101, 'kabupatenkota'=> 'KABUPATEN MALUKU TENGGARA BARAT', 'objectprovinsifk'=> 81],
            ['id'=> 8102, 'kabupatenkota'=> 'KABUPATEN MALUKU TENGGARA', 'objectprovinsifk'=> 81],
            ['id'=> 8103, 'kabupatenkota'=> 'KABUPATEN MALUKU TENGAH', 'objectprovinsifk'=> 81],
            ['id'=> 8104, 'kabupatenkota'=> 'KABUPATEN BURU', 'objectprovinsifk'=> 81],
            ['id'=> 8105, 'kabupatenkota'=> 'KABUPATEN KEPULAUAN ARU', 'objectprovinsifk'=> 81],
            ['id'=> 8106, 'kabupatenkota'=> 'KABUPATEN SERAM BAGIAN BARAT', 'objectprovinsifk'=> 81],
            ['id'=> 8107, 'kabupatenkota'=> 'KABUPATEN SERAM BAGIAN TIMUR', 'objectprovinsifk'=> 81],
            ['id'=> 8108, 'kabupatenkota'=> 'KABUPATEN MALUKU BARAT DAYA', 'objectprovinsifk'=> 81],
            ['id'=> 8109, 'kabupatenkota'=> 'KABUPATEN BURU SELATAN', 'objectprovinsifk'=> 81],
            ['id'=> 8171, 'kabupatenkota'=> 'KOTA AMBON', 'objectprovinsifk'=> 81],
            ['id'=> 8172, 'kabupatenkota'=> 'KOTA TUAL', 'objectprovinsifk'=> 81],
            ['id'=> 8201, 'kabupatenkota'=> 'KABUPATEN HALMAHERA BARAT', 'objectprovinsifk'=> 82],
            ['id'=> 8202, 'kabupatenkota'=> 'KABUPATEN HALMAHERA TENGAH', 'objectprovinsifk'=> 82],
            ['id'=> 8203, 'kabupatenkota'=> 'KABUPATEN KEPULAUAN SULA', 'objectprovinsifk'=> 82],
            ['id'=> 8204, 'kabupatenkota'=> 'KABUPATEN HALMAHERA SELATAN', 'objectprovinsifk'=> 82],
            ['id'=> 8205, 'kabupatenkota'=> 'KABUPATEN HALMAHERA UTARA', 'objectprovinsifk'=> 82],
            ['id'=> 8206, 'kabupatenkota'=> 'KABUPATEN HALMAHERA TIMUR', 'objectprovinsifk'=> 82],
            ['id'=> 8207, 'kabupatenkota'=> 'KABUPATEN PULAU MOROTAI', 'objectprovinsifk'=> 82],
            ['id'=> 8208, 'kabupatenkota'=> 'KABUPATEN PULAU TALIABU', 'objectprovinsifk'=> 82],
            ['id'=> 8271, 'kabupatenkota'=> 'KOTA TERNATE', 'objectprovinsifk'=> 82],
            ['id'=> 8272, 'kabupatenkota'=> 'KOTA TIDORE KEPULAUAN', 'objectprovinsifk'=> 82],
            ['id'=> 9101, 'kabupatenkota'=> 'KABUPATEN FAKFAK', 'objectprovinsifk'=> 91],
            ['id'=> 9102, 'kabupatenkota'=> 'KABUPATEN KAIMANA', 'objectprovinsifk'=> 91],
            ['id'=> 9103, 'kabupatenkota'=> 'KABUPATEN TELUK WONDAMA', 'objectprovinsifk'=> 91],
            ['id'=> 9104, 'kabupatenkota'=> 'KABUPATEN TELUK BINTUNI', 'objectprovinsifk'=> 91],
            ['id'=> 9105, 'kabupatenkota'=> 'KABUPATEN MANOKWARI', 'objectprovinsifk'=> 91],
            ['id'=> 9106, 'kabupatenkota'=> 'KABUPATEN SORONG SELATAN', 'objectprovinsifk'=> 91],
            ['id'=> 9107, 'kabupatenkota'=> 'KABUPATEN SORONG', 'objectprovinsifk'=> 91],
            ['id'=> 9108, 'kabupatenkota'=> 'KABUPATEN RAJA AMPAT', 'objectprovinsifk'=> 91],
            ['id'=> 9109, 'kabupatenkota'=> 'KABUPATEN TAMBRAUW', 'objectprovinsifk'=> 91],
            ['id'=> 9110, 'kabupatenkota'=> 'KABUPATEN MAYBRAT', 'objectprovinsifk'=> 91],
            ['id'=> 9111, 'kabupatenkota'=> 'KABUPATEN MANOKWARI SELATAN', 'objectprovinsifk'=> 91],
            ['id'=> 9112, 'kabupatenkota'=> 'KABUPATEN PEGUNUNGAN ARFAK', 'objectprovinsifk'=> 91],
            ['id'=> 9171, 'kabupatenkota'=> 'KOTA SORONG', 'objectprovinsifk'=> 91],
            ['id'=> 9401, 'kabupatenkota'=> 'KABUPATEN MERAUKE', 'objectprovinsifk'=> 94],
            ['id'=> 9402, 'kabupatenkota'=> 'KABUPATEN JAYAWIJAYA', 'objectprovinsifk'=> 94],
            ['id'=> 9403, 'kabupatenkota'=> 'KABUPATEN JAYAPURA', 'objectprovinsifk'=> 94],
            ['id'=> 9404, 'kabupatenkota'=> 'KABUPATEN NABIRE', 'objectprovinsifk'=> 94],
            ['id'=> 9408, 'kabupatenkota'=> 'KABUPATEN KEPULAUAN YAPEN', 'objectprovinsifk'=> 94],
            ['id'=> 9409, 'kabupatenkota'=> 'KABUPATEN BIAK NUMFOR', 'objectprovinsifk'=> 94],
            ['id'=> 9410, 'kabupatenkota'=> 'KABUPATEN PANIAI', 'objectprovinsifk'=> 94],
            ['id'=> 9411, 'kabupatenkota'=> 'KABUPATEN PUNCAK JAYA', 'objectprovinsifk'=> 94],
            ['id'=> 9412, 'kabupatenkota'=> 'KABUPATEN MIMIKA', 'objectprovinsifk'=> 94],
            ['id'=> 9413, 'kabupatenkota'=> 'KABUPATEN BOVEN DIGOEL', 'objectprovinsifk'=> 94],
            ['id'=> 9414, 'kabupatenkota'=> 'KABUPATEN MAPPI', 'objectprovinsifk'=> 94],
            ['id'=> 9415, 'kabupatenkota'=> 'KABUPATEN ASMAT', 'objectprovinsifk'=> 94],
            ['id'=> 9416, 'kabupatenkota'=> 'KABUPATEN YAHUKIMO', 'objectprovinsifk'=> 94],
            ['id'=> 9417, 'kabupatenkota'=> 'KABUPATEN PEGUNUNGAN BINTANG', 'objectprovinsifk'=> 94],
            ['id'=> 9418, 'kabupatenkota'=> 'KABUPATEN TOLIKARA', 'objectprovinsifk'=> 94],
            ['id'=> 9419, 'kabupatenkota'=> 'KABUPATEN SARMI', 'objectprovinsifk'=> 94],
            ['id'=> 9420, 'kabupatenkota'=> 'KABUPATEN KEEROM', 'objectprovinsifk'=> 94],
            ['id'=> 9426, 'kabupatenkota'=> 'KABUPATEN WAROPEN', 'objectprovinsifk'=> 94],
            ['id'=> 9427, 'kabupatenkota'=> 'KABUPATEN SUPIORI', 'objectprovinsifk'=> 94],
            ['id'=> 9428, 'kabupatenkota'=> 'KABUPATEN MAMBERAMO RAYA', 'objectprovinsifk'=> 94],
            ['id'=> 9429, 'kabupatenkota'=> 'KABUPATEN NDUGA', 'objectprovinsifk'=> 94],
            ['id'=> 9430, 'kabupatenkota'=> 'KABUPATEN LANNY JAYA', 'objectprovinsifk'=> 94],
            ['id'=> 9431, 'kabupatenkota'=> 'KABUPATEN MAMBERAMO TENGAH', 'objectprovinsifk'=> 94],
            ['id'=> 9432, 'kabupatenkota'=> 'KABUPATEN YALIMO', 'objectprovinsifk'=> 94],
            ['id'=> 9433, 'kabupatenkota'=> 'KABUPATEN PUNCAK', 'objectprovinsifk'=> 94],
            ['id'=> 9434, 'kabupatenkota'=> 'KABUPATEN DOGIYAI', 'objectprovinsifk'=> 94],
            ['id'=> 9435, 'kabupatenkota'=> 'KABUPATEN INTAN JAYA', 'objectprovinsifk'=> 94],
            ['id'=> 9436, 'kabupatenkota'=> 'KABUPATEN DEIYAI', 'objectprovinsifk'=> 94],
            ['id'=> 9471, 'kabupatenkota'=> 'KOTA JAYAPURA', 'objectprovinsifk'=> 94],
        ];

        foreach ($kabupatenKota as $item) {
            DB::table('kabupatenkota_m')->insert([
                'id' => $item['id'],
                'kdprofile' => 10,
                'statusenabled' => true,
                'kabupatenkota' => $item['kabupatenkota'],
                'objectprovinsifk' => $item['objectprovinsifk'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
