<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PegawaiMSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('pegawai_m')->insert([
            [
                'kdprofile' => 10,
                'statusenabled' => true,
                'namalengkap' => 'John Doe',
                'jeniskelaminfk' => 1,
                'tanggal_lahir' => Carbon::parse('1990-01-01'),
                'tempat_lahir' => 'Jakarta',
                'no_handphone' => '08123456789',
                'alamat' => 'Jl. Merdeka No. 1',
                'email' => 'john.doe@example.com',
                'nik' => '3201010101010001',
                'nip' => '198001011990011001',
                'nuptk' => '1234567890',
                'status_kepegawaian' => 1,
                'jabatan' => 'Guru Kelas',
                'tmt_jabatan' => Carbon::parse('2020-07-01'),
                'tmt_pengangkatan' => Carbon::parse('2020-08-01'),
                'sk_pengangkatan' => 'SK2020/001',
                'tahun_masuk' => 2015,
                'foto' => null,
                'agamafk' => 1,
                'kelasfk' => 2,
                'objectjenispegawaifk' => 1,
                'objectpendidikanterakhirfk' => 4,
                'objectnegarafk' => 1,
                'is_wali_kelas' => true,
                'kelas_wali' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kdprofile' => 10,
                'statusenabled' => true,
                'namalengkap' => 'Jane Smith',
                'jeniskelaminfk' => 2,
                'tanggal_lahir' => Carbon::parse('1985-05-10'),
                'tempat_lahir' => 'Bandung',
                'no_handphone' => '08213456789',
                'alamat' => 'Jl. Sudirman No. 10',
                'email' => 'jane.smith@example.com',
                'nik' => '3201010101010002',
                'nip' => '198505101990021002',
                'nuptk' => '2234567890',
                'status_kepegawaian' => 2,
                'jabatan' => 'Guru Bahasa',
                'tmt_jabatan' => Carbon::parse('2018-01-01'),
                'tmt_pengangkatan' => Carbon::parse('2018-02-01'),
                'sk_pengangkatan' => 'SK2018/045',
                'tahun_masuk' => 2018,
                'foto' => null,
                'agamafk' => 2,
                'kelasfk' => 3,
                'objectjenispegawaifk' => 2,
                'objectpendidikanterakhirfk' => 3,
                'objectnegarafk' => 1,
                'is_wali_kelas' => false,
                'kelas_wali' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kdprofile' => 10,
                'statusenabled' => true,
                'namalengkap' => 'Ahmad Fauzi',
                'jeniskelaminfk' => 1,
                'tanggal_lahir' => Carbon::parse('1980-11-11'),
                'tempat_lahir' => 'Surabaya',
                'no_handphone' => '08124567891',
                'alamat' => 'Jl. Pahlawan No. 5',
                'email' => 'ahmad.fauzi@example.com',
                'nik' => '3201010101010003',
                'nip' => '198011111990031003',
                'nuptk' => '3234567890',
                'status_kepegawaian' => 3,
                'jabatan' => 'Kepala Sekolah',
                'tmt_jabatan' => Carbon::parse('2015-01-01'),
                'tmt_pengangkatan' => Carbon::parse('2015-03-01'),
                'sk_pengangkatan' => 'SK2015/078',
                'tahun_masuk' => 2010,
                'foto' => null,
                'agamafk' => 1,
                'kelasfk' => 1,
                'objectjenispegawaifk' => 3,
                'objectpendidikanterakhirfk' => 5,
                'objectnegarafk' => 1,
                'is_wali_kelas' => false,
                'kelas_wali' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kdprofile' => 10,
                'statusenabled' => true,
                'namalengkap' => 'Siti Nurhaliza',
                'jeniskelaminfk' => 2,
                'tanggal_lahir' => Carbon::parse('1992-07-22'),
                'tempat_lahir' => 'Bekasi',
                'no_handphone' => '08135566789',
                'alamat' => 'Jl. Melati No. 8',
                'email' => 'siti.nurhaliza@example.com',
                'nik' => '3201010101010004',
                'nip' => '199207221991041004',
                'nuptk' => '4234567890',
                'status_kepegawaian' => 4,
                'jabatan' => 'Guru Matematika',
                'tmt_jabatan' => Carbon::parse('2021-01-01'),
                'tmt_pengangkatan' => Carbon::parse('2021-03-01'),
                'sk_pengangkatan' => 'SK2021/012',
                'tahun_masuk' => 2021,
                'foto' => null,
                'agamafk' => 3,
                'kelasfk' => 4,
                'objectjenispegawaifk' => 2,
                'objectpendidikanterakhirfk' => 4,
                'objectnegarafk' => 1,
                'is_wali_kelas' => true,
                'kelas_wali' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kdprofile' => 10,
                'statusenabled' => true,
                'namalengkap' => 'Dedi Mulyadi',
                'jeniskelaminfk' => 1,
                'tanggal_lahir' => Carbon::parse('1988-03-30'),
                'tempat_lahir' => 'Depok',
                'no_handphone' => '08123499887',
                'alamat' => 'Jl. Kenanga No. 20',
                'email' => 'dedi.mulyadi@example.com',
                'nik' => '3201010101010005',
                'nip' => '198803301992051005',
                'nuptk' => '5234567890',
                'status_kepegawaian' => 5,
                'jabatan' => 'Guru PJOK',
                'tmt_jabatan' => Carbon::parse('2019-01-01'),
                'tmt_pengangkatan' => Carbon::parse('2019-02-01'),
                'sk_pengangkatan' => 'SK2019/032',
                'tahun_masuk' => 2019,
                'foto' => null,
                'agamafk' => 2,
                'kelasfk' => 5,
                'objectjenispegawaifk' => 2,
                'objectpendidikanterakhirfk' => 3,
                'objectnegarafk' => 1,
                'is_wali_kelas' => false,
                'kelas_wali' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],    
        ]);
    }
}
